# Generated by Django 3.2.25 on 2025-02-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Bonus', 'Bonus'), ('Deduction', 'Deduction')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary_app.employee')),
            ],
        ),
    ]
